name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Default
    - name: Default upload step
      run: echo Upload successfully
      
    # Test
    - name: Set up Python
      if: contains(github.event.head_commit.message, 'run-test')
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      if: contains(github.event.head_commit.message, 'run-test')
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pygame
        
    - name: Run tests
      if: contains(github.event.head_commit.message, 'run-test')
      run: |
        cd src
        pytest
