name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    
    steps:
    - uses: actions/checkout@v3
    
    # Default
    - name: Default upload step
      run: echo Upload successfully
      
    # Test
    - name: Set up Python
      if: contains(github.event.head_commit.message, 'run-test')
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      if: contains(github.event.head_commit.message, 'run-test')
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pygame
        
    - name: Run tests
      if: contains(github.event.head_commit.message, 'run-test')
      run: |
        pytest
=======
    steps:
      # Checkout repository code
      - uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pygame
          # Add any other dependencies your project needs
          pip install -r requirements.txt || true

      # Change directory and run pytest
      - name: Run pytest
        run: |
          cd src
          pytest -v test_main.py

      # Upload test results
      - name: Check Upload
        if: always()  # This ensures the step runs even if tests fail
        run: |
          echo "Upload Successfully!"
>>>>>>> 1fbfab39e3a18b6fe350cc254611d76c8351690f
